package schema

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// DatabaseInstaller handles the execution of SQL migration and seed files
type DatabaseInstaller struct {
	SchemaPath string
	AdminEmail string
	AdminName  string
}

// NewDatabaseInstaller creates a new database installer instance
func NewDatabaseInstaller(schemaPath, adminEmail, adminName string) *DatabaseInstaller {
	return &DatabaseInstaller{
		SchemaPath: schemaPath,
		AdminEmail: adminEmail,
		AdminName:  adminName,
	}
}

// GenerateInstallationScript creates a complete SQL script from migrations and seeds
func (di *DatabaseInstaller) GenerateInstallationScript() (string, error) {
	var sqlScript strings.Builder

	// Add header
	sqlScript.WriteString("-- Dvarpala Database Installation Script\n")
	sqlScript.WriteString("-- Generated by Frigga Labs Installer\n")
	sqlScript.WriteString("-- =====================================\n\n")

	// Execute migrations first
	migrations, err := di.getMigrationFiles()
	if err != nil {
		return "", fmt.Errorf("failed to get migration files: %v", err)
	}

	sqlScript.WriteString("-- MIGRATIONS\n")
	sqlScript.WriteString("-- -----------\n\n")

	for _, migration := range migrations {
		content, err := os.ReadFile(migration)
		if err != nil {
			return "", fmt.Errorf("failed to read migration file %s: %v", migration, err)
		}

		sqlScript.WriteString(fmt.Sprintf("-- Migration: %s\n", filepath.Base(migration)))
		sqlScript.WriteString(string(content))
		sqlScript.WriteString("\n\n")
	}

	// Execute seeds
	seeds, err := di.getSeedFiles()
	if err != nil {
		return "", fmt.Errorf("failed to get seed files: %v", err)
	}

	sqlScript.WriteString("-- SEEDS\n")
	sqlScript.WriteString("-- -----\n\n")

	for _, seed := range seeds {
		content, err := os.ReadFile(seed)
		if err != nil {
			return "", fmt.Errorf("failed to read seed file %s: %v", seed, err)
		}

		sqlScript.WriteString(fmt.Sprintf("-- Seed: %s\n", filepath.Base(seed)))
		sqlScript.WriteString(string(content))
		sqlScript.WriteString("\n\n")
	}

	// Add admin user creation with dynamic values
	sqlScript.WriteString("-- Dynamic Admin User Creation\n")
	sqlScript.WriteString("-- ----------------------------\n\n")
	sqlScript.WriteString(di.generateAdminUserSQL())

	return sqlScript.String(), nil
}

// getMigrationFiles returns sorted list of migration files
func (di *DatabaseInstaller) getMigrationFiles() ([]string, error) {
	migrationsPath := filepath.Join(di.SchemaPath, "migrations")
	var files []string

	err := filepath.WalkDir(migrationsPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".sql") {
			files = append(files, path)
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	// Sort files to ensure proper execution order
	sort.Strings(files)
	return files, nil
}

// getSeedFiles returns sorted list of seed files
func (di *DatabaseInstaller) getSeedFiles() ([]string, error) {
	seedsPath := filepath.Join(di.SchemaPath, "seeds")
	var files []string

	err := filepath.WalkDir(seedsPath, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".sql") {
			files = append(files, path)
		}
		return nil
	})

	if err != nil {
		return nil, err
	}

	// Sort files to ensure proper execution order
	sort.Strings(files)
	return files, nil
}

// generateAdminUserSQL creates the SQL for inserting the admin user with dynamic values
func (di *DatabaseInstaller) generateAdminUserSQL() string {
	return fmt.Sprintf(`-- Insert admin user with configuration values
INSERT INTO users (email, full_name, is_admin, is_active) 
VALUES ('%s', '%s', true, true) 
ON CONFLICT (email) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    is_admin = true,
    is_active = true,
    updated_at = CURRENT_TIMESTAMP;

-- Assign admin user to administrators group
INSERT INTO user_groups (user_id, group_id, assigned_by)
SELECT u.id, g.id, u.id
FROM users u, groups g
WHERE u.email = '%s' AND g.name = 'administrators'
ON CONFLICT (user_id, group_id) DO NOTHING;
`, di.AdminEmail, di.AdminName, di.AdminEmail)
}

// WriteInstallationScript writes the complete installation script to a file
func (di *DatabaseInstaller) WriteInstallationScript(outputPath string) error {
	script, err := di.GenerateInstallationScript()
	if err != nil {
		return err
	}

	return os.WriteFile(outputPath, []byte(script), 0644)
}